server:
  port: 8082
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/projgo_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: projgo-backend
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

